name: soulmaskserver

services:
  soulmaskserver:
    image: ghcr.io/papabeardoes/soulmaskserver:latest
    container_name: soulmaskserver
    restart: unless-stopped
    mem_limit: 20G
    deploy:
      resources:
        limits:
          memory: 20G
    environment:
      SOULMASK_SERVERNAME: Server Name
      SOULMASK_STEAM_VALIDATE: false
      SOULMASK_PASSWORD: ${SOULMASK_PASSWORD}
      SOULMASK_ADMIN_PASSWORD: ${SOULMASK_ADMIN_PASSWORD}
      SOULMASK_MAXPLAYERS: 25
      SOULMASK_PVE: true
      #SOULMASK_<some_key>: "some value"
    user: 10000:10000
    volumes:
      - soulmask_vol:/home/soulmask/server
    networks:
      - soulmask_net
    ports:
      - 8777:8777/udp
      - 27015:27015/udp
      - 18888:18888/udp

volumes:
  soulmask_vol:
    name: soulmaskserver

networks:
  soulmask_net:
    driver: bridge
    attachable: true